apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: hvfs-vn-tls
spec:
  secretName: hvfs-vn
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hvfs.vn
  dnsNames:
    - hvfs.vn
    - www.hvfs.vn